[package]
name = "rust-desktop-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.13.1", features = ["system", "tokio"] }
reqwest = { version = "0.12.9", features = ["json"] }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
tokio = "1.42.0"
